config/routes.rb
Site::Application.routes.draw do
  
  root :to => "posts#index"
  
  match 'blog'      => "posts#index", :as => :blog
  match "/blog/:id" => "posts#show",  :as => :post
  
  match 'search'  => "static#search", :as => :search
  
  resources :user_sessions
  match 'login'   => "user_sessions#new",     :as => :login
  match 'logout'  => "user_sessions#destroy", :as => :logout
  
  namespace :bo do
    match 'dashboard' => "dashboard#index"
    resources :users
    resources :tags
    resources :categories
    resources :posts
    resources :images
    resources :galleries do 
      match "/add_image/:id"    => "galleries#add_image",     :via => :post,    :as => :add_image
      match "/delete_image/:id" => "galleries#delete_image",  :via => :delete,  :as => :delete_image
    end
    namespace :ajax do
      post 'kramdown_to_html' => 'base#kramdown_to_html'
      resources :galleries, :only => [] do 
        match "/image_pos/:id"    => "galleries#image_pos", :via => :post, :as => :image_pos
      end
    end
  end
  
  mathjax 'mathjax'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  # Post.statuses get all status
  as_enum :status, [:draft, :pending_review, :published], :strings => true
  
  has_attached_file :featured_image, :styles => {:thumb => "100x100#", :large => '970x350#' }
  attr_accessible :body_html, :intro_text, :body_kd, :published_at, :featured_image, :status, :title, :category_id, :tag_names, :gallery_id
  attr_accessor :tag_names
  
  belongs_to :category
  belongs_to :gallery
  has_and_belongs_to_many :tags, :uniq => true, :validate => true
  
  validates :status, :published_at, :presence => true
  validates :status, :as_enum => true
  validates_attachment :featured_image,
  :content_type => { :content_type => %w"image/jpg image/jpeg image/pjpeg image/gif image/png image/svg+xml image/tiff" },
  :size => { :in => 0..4.megabytes }
  
  before_validation :parse_body_kd_to_html
  before_validation :set_tags_by_tag_names

  #
  #
  #
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  #
  #
  #
  def tag_selectize_options merge=[]
    array = self.tags.all.map{ |tag| { :text => tag.name, :value => tag.name } }
    self.tag_names.split(',').each{ |tag_name| array << { :text => tag_name, :value => tag_name } }
    array += merge
    array.uniq
  end
  
  def tag_selectize_values
    self.tags.map{ |tag| tag.name }.join(',')
  end

  private
  def parse_body_kd_to_html
    self.body_html = Kramdown::Document.new(self.body_kd, :input => 'kramdown').to_html
  end
  
  def set_tags_by_tag_names
    return if self.tag_names.nil?
    self.tags = []
    self.tag_names.split(',').each do |tag_name|
      self.tags << ( Tag.find_by_name(tag_name) || Tag.new(:name => tag_name) )
    end
  end  
  
end

app/controllers/bo/ajax/base_controller.rb
class Bo::Ajax::BaseController < Bo::BaseController
  layout false
  
  def kramdown_to_html
    str = params[:str]
    html = Kramdown::Document.new(str, :input => 'kramdown').to_html
    render :text => html
  end
end

app/controllers/bo/ajax/galleries_controller.rb
class Bo::Ajax::GalleriesController < Bo::Ajax::BaseController
  
  def image_pos
    gallery = Gallery.find(params[:gallery_id])
    image = Image.find(params[:id])
    
    gallery_image = gallery.gallery_images.where(:image_id => image.id).first
    pos = params[:pos].to_i
    
    if gallery_image.blank? || pos.blank?
      text = ""
      text += "gallery_image is blank" if gallery_image.blank?
      text += ", pos is blank" if pos.blank?
      text += ", gallery is #{gallery.id}"
      text += ", image is #{image.id}"
      
      render :json => { :status => false, :error => text}
    else
      gallery_image.insert_at(pos)
      render :json => { :status => true}
    end
  end
  
end

app/controllers/bo/ajax_controller.rb
class Bo::AjaxController < Bo::BaseController
  layout :false
  
  def kramdown_to_html
    str = params[:str]
    html = Kramdown::Document.new(str, :input => 'kramdown').to_html
    render :text => html
  end
end

app/controllers/bo/base_controller.rb
class Bo::BaseController < ApplicationController
  layout 'application_bo'
  before_filter :require_user
end

app/controllers/bo/categories_controller.rb
class Bo::CategoriesController < Bo::BaseController
  def index
    @categories = Category.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
   
    if @category.save
      redirect_to [:bo, @category], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Category))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
   
    if @category.update_attributes(params[:category])
      redirect_to [:bo, @category], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Category))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
   
    redirect_to bo_categories_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Category))
  end
end

app/controllers/bo/dashboard_controller.rb
class Bo::DashboardController < Bo::BaseController
  def index
  end
end

app/controllers/bo/galleries_controller.rb
class Bo::GalleriesController < Bo::BaseController
  def index
    @galleries = Gallery.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @gallery = Gallery.find(params[:id])
    @images = Image.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def new
    @gallery = Gallery.new
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end
  
  def create
    @gallery = Gallery.new(params[:gallery])
   
    if @gallery.save
      redirect_to [:bo, @gallery], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Gallery))
    else
      render :action => "new" 
    end
  end
  
  def update
    @gallery = Gallery.find(params[:id])
   
    if @gallery.update_attributes(params[:gallery])
      redirect_to [:bo, @gallery], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Gallery))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
   
    redirect_to bo_galleries_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Gallery))
  end
  
  def add_image
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.find(params[:id])
    
    @gallery.images << @image
    redirect_to bo_gallery_url(@gallery, :page => params[:page])
  end
  
  def delete_image
    @gallery = params[:gallery_id] ? Gallery.find(params[:gallery_id]) : nil
    @image = Image.find(params[:id])
    
    @gallery.images.delete(@image)
    redirect_to bo_gallery_url(@gallery, :page => params[:page])
  end
  
end

app/controllers/bo/images_controller.rb
class Bo::ImagesController < Bo::BaseController
  def index
    @images = Image.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @image = Image.find(params[:id])
  end
  
  def new
    @image = Image.new
  end
  
  def create
    @image = Image.new(params[:image])
    
    if @image.save
      redirect_to [:bo, @image], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Image))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @image = Image.find(params[:id])
  end
  
  def update
    @image = Image.find(params[:id])
   
    if @image.update_attributes(params[:image])
      redirect_to [:bo, @image], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Image))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @image = Image.find(params[:id])

    @image.destroy
    redirect_to bo_images_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Image))
  end
end

app/controllers/bo/posts_controller.rb
class Bo::PostsController < Bo::BaseController
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE).order('published_at DESC')
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
    @post.tag_names = @post.tag_selectize_values
  end
  
  def create
    @post = Post.new(params[:post])
   
    if @post.save
      redirect_to [:bo, @post], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Post))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    @post.tag_names = @post.tag_selectize_values
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update_attributes(params[:post])
      redirect_to [:bo, @post], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Post))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
   
    redirect_to bo_posts_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Post))
  end
end

app/controllers/bo/tags_controller.rb
class Bo::TagsController < Bo::BaseController
  def index
    @tags = Tag.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @tag = Tag.find(params[:id])
  end
  
  def new
    @tag = Tag.new
  end
  
  def create
    @tag = Tag.new(params[:tag])
   
    if @tag.save
      redirect_to [:bo, @tag], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Tag))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @tag = Tag.find(params[:id])
  end
  
  def update
    @tag = Tag.find(params[:id])
   
    if @tag.update_attributes(params[:tag])
      redirect_to [:bo, @tag], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Tag))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
   
    redirect_to bo_tags_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Tag))
  end
end

app/controllers/bo/users_controller.rb
class Bo::UsersController < Bo::BaseController
  def index
    @users = User.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
   
    if @user.save
      redirect_to [:bo, @user], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(User))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
   
    if @user.update_attributes(params[:user])
      redirect_to [:bo, @user], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(User))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
   
    redirect_to bo_users_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(User))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(:status_cd => Post.status_published)
      .paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
      .order('published_at DESC')
      .includes(:category)
      .includes(:tags)
  end
  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/bo/categories_helper.rb
module Bo::CategoriesHelper
end

app/helpers/bo/images_helper.rb
module Bo::ImagesHelper
  def image_dropdown_styles_button image
    btn = button_tag :class => 'btn btn-default dropdown-toggle', 'data-toggle' => "dropdown" do
      content_tag(:span, nil, :class => "glyphicon glyphicon-paperclip") +
      " " +
      content_tag(:span, nil, :class => 'caret')
    end
    
    links = content_tag :ul, :class => 'dropdown-menu align-left', :role => 'menu' do
      Image::STYLES.each do |key, value|
        concat content_tag(:li, (link_to key, 'javascript:void(0)', :onclick => "window.prompt ('#{tview('copy_to_clipboard')}', '#{path_to_image image.image.url(key)}');"))
      end
      concat content_tag(:li, (link_to 'original', 'javascript:void(0)', :onclick => "window.prompt ('#{tview('copy_to_clipboard')}', '#{path_to_image image.image.url}');"))
    end
    
    content_tag(:div, btn+links, :class => 'btn-group')
  end
end

app/helpers/bo/posts_helper.rb
module Bo::PostsHelper
  
  #
  #
  #
  def label_by_post_status status
    label_type = case status
      when :published then 'label-success'
      when :pending_review then 'label-warning'
      when :draft then 'label-default'
      else '' end
    
    "<span class='label #{label_type}'>#{Post.human_enum_name :statuses, status}</span>".html_safe
  end
  
  #
  #
  #
  def tag_list tags
    html = '<div class="tag-list">'
    html += tags.map.each{|tag| "<span class='tag'>#{tag.name}</span>"}.join(' ')
    html += '</div>'
    html.html_safe
  end
  
end

app/helpers/bo/tags_helper.rb
module Bo::TagsHelper
end

app/helpers/bo/users_helper.rb
module Bo::UsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  ###############################################
  # HTML
  ###############################################
  #
  #
  #
  def date_icon_and_text post
    date = l post.published_at, :format => :short_2
    "<p class='icon-and-text'><span class='glyphicon glyphicon-calendar icon'></span><span>#{date}</span></p>".html_safe
  end

  #
  #
  #
  def category_icon_and_text post
    link = if post.category.blank? 
      tview('uncategorized')
    else
      link_to post.category.name, search_path(:category => post.category.id)
    end
    "<p class='icon-and-text'><span class='glyphicon glyphicon-folder-open icon'></span><span>#{link}</span></p>".html_safe
  end
  #
  # Return the icon with text Tag or Tags
  #
  def tag_icon_and_text post
    icon = post.tags.length <= 1 ? 'glyphicon-tag' : 'glyphicon-tags'
    "<p class='icon-and-text'><span class='glyphicon #{icon} icon'></span><span>#{pluralize(post.tags.length, I18n.tmodel(Tag))}</span></p>".html_safe
  end
  
  #
  # Return the button links for tags
  #
  def tag_buttons post
    return '' if post.tags.blank?
    
    html = ''
    for tag in post.tags
      html += link_to tag.name, search_path(:tags => tag.id), :class => 'button'
    end
    
    return html.html_safe
  end
end

app/views/bo/posts/_form.html.erb
<%# PARAMS: post
%>

<%= render 'bo/shared/errors', :target => post %>

<%= form_for [:bo, post], :html => {:class => 'form-horizontal'} do |f| %>
  <div class="row">
    <div class="col-md-12">
      <form class="form-horizontal" role="form">
        <div class="form-group">
          <%= f.label :title, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-5">
            <%= f.text_field :title, :class => 'form-control', :autofocus => true %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :intro_text, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-5">
            <%= f.text_field :intro_text, :class => 'form-control', :autofocus => true %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :featured_image, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.file_field :featured_image, :class => '' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :status, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.select :status, Post.statuses_for_select, {}, :class => 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :category_id, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-5">
            <%= f.collection_select :category_id, Category.all, :id, :name, {:include_blank => true}, :class => 'form-control selectize' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :tag_names, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-5">
            <%= f.text_field :tag_names, :class => 'form-control selectize' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :published_at, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-8">
            <%= f.datetime_select :published_at, {}, :class => '' %>
          </div>
        </div>
        
        <div class="form-group">
          <%= f.label :gallery_id, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-5">
            <%= f.collection_select :gallery_id, Gallery.all, :id, :name, {:include_blank => true}, :class => 'form-control selectize' %>
          </div>
        </div>
        
        <div id="post-fullscreen">
          <div class="form-group">
            <%= f.label :body_kd, :class => 'col-sm-2 control-label' %>
            <div class="col-sm-5">
              <ul class="nav nav-pills">
                <li><a href="#post-code" data-toggle="tab">Code</a></li>
                <li><a href="#post-preview" data-toggle="tab">Preview</a></li>
              </ul>
            </div>
          </div>
          
          <div class="tab-content">
            <div class="tab-pane" id="post-code">
              <div class="form-group">
                <div class="col-sm-12">
                  <%= f.text_area :body_kd, :class => 'form-control code' %>
                </div>
              </div>
            </div>
            <div class="tab-pane" id="post-preview">
              <div class="form-group">
                <div class="col-sm-12">
                  <div class="post-preview"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
<% end %>

<script>
$(document).ready(function(){
  //--------
  // don't use 'class="active"' for use callbacks on the first show
  //--------
  
  // --- the callbacks
  $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
    //e.target // activated tab
    //e.relatedTarget // previous tab
    $('#post-preview div.post-preview').html('');
    if( $(e.target).attr('href') == '#post-preview' ){
      var str = $('#post-code textarea').val();
      $.ajax({
        type: "POST",
        url: '<%= bo_ajax_kramdown_to_html_path %>',
        data: {'str' : str },
        success: function(data, textStatus, jqXHR){
          $('#post-preview div.post-preview').html(data);
          MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
          Prism.highlightAll();
        }
      });
    }
  });
  
  // --- first show
  $('a[href="#post-code"]').tab('show');
  
  //--------
  // autogrow
  //--------
  $('#post_body_kd').autogrow({onInitialize: true});
  
  //--------
  // selectize
  //--------
  $('#post_status').selectize({
    create: true,
    sortField: 'text'
  });
  $('#post_category_id').selectize({
    create: true,
    sortField: 'text'
  });
  $('#post_tag_names').selectize({
    plugins: ['remove_button'],
    delimiter: ',',
    persist: false,
    create: true,
    options: <%= post.tag_selectize_options(Tag.to_selectize_options).to_json.html_safe %>
  });
  
  
  $('#post_gallery_id').selectize({
    create: true,
    sortField: 'name',
    valueField: 'id',
    labelField: 'name',
    searchField: ['name', 'description'],
    options: <%= (Gallery.to_selectize_options).to_json.html_safe %>,
    render:{
      item: function(item, escape){
        return '<span>' + escape(item.name) + '</span>'
      },
      option: function(item, escape) {
        var imgTag = item.thumb ? '<img src="' + escape(item.thumb) + '" alt=""/>' : '<div></div>';
        var thereAreText = "<%= t 'there_are_n_images_in_gallery' %>";
        return '<table class="selectize-post-gallery">' +
                  '<tr>' +
                    '<td rowspan="3" class="image">' + imgTag + '</td>' +
                    '<td class="title"><span>' + escape(item.name) + '</span></td>' +
                  '</tr>' +
                  '<tr>' +
                    '<td class="description"><span>' + escape(item.description) + '</span></td>' +
                  '</tr>' +
                  '<tr>' +
                    '<td class="number"><span>' + thereAreText.replace('%n_images%', escape(item.n_images)) + '</span></td>' +
                  '</tr>' +
                '</table>';
      }
    }
  });
});
</script>

app/views/bo/posts/edit.html.erb
<% content_for_header I18n.tmodel(Post), tview('edit_post') %>

<div class="row action-buttons">
  <div class="col-xs-7 col-md-7">
    <%= link_to I18n.tbtn('cancel'), bo_post_path(@post), :class => 'btn btn-default' %>
  </div>
  <div class="col-xs-5 col-md-5 align-right">
    <div class="btn-group">
      <%= link_to 'javascript:void(0)', :class => 'btn btn-primary', :onclick => '$("form").submit()' do %>
        <span class="glyphicon glyphicon-floppy-disk"></span>
      <% end %>
    </div>
  </div>
</div>

<%= render 'form', :post => @post %>

app/views/bo/posts/index.html.erb
<% content_for_header I18n.tmodel(Post), tview('list_of_posts') %>

<div class="row">
  <div class="col-md-12">
    <%= link_to I18n.tbtn('add_new'), new_bo_post_path, :class => 'btn btn-default' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-condensed table-striped">
      <thead>
        <tr>
          <th><%= I18n.tattr(Post, :status) %></th>
          <th><%= I18n.tattr(Post, :published_at) %></th>
          <th><%= I18n.tattr(Post, :title) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% for post in @posts %>
          <tr>
            <td><%= label_by_post_status post.status %></td>
            <td><%= l( post.published_at, :format => :short ) %></td>
            <td><%= post.title %></td>
            <td class="align-right btn-group-for-3-btns">
              <div class="btn-group">
                <%= link_to bo_post_path(post), :class => 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-eye-open"></span>
                <% end %>
                <%= link_to edit_bo_post_path(post), :class => 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                <% end %>
                <%= link_to bo_post_path(post), :class => 'btn btn-danger', :confirm => I18n.tmsg('are_you_sure'), :method => :delete do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/bo/posts/new.html.erb
<% content_for_header I18n.tmodel(Post), tview('new_post') %>

<div class="row action-buttons">
  <div class="col-xs-7 col-md-7">
    <%= link_to I18n.tbtn('cancel'), bo_posts_path, :class => 'btn btn-default' %>
  </div>
  <div class="col-xs-5 col-md-5 align-right">
    <div class="btn-group">
      <%= link_to 'javascript:void(0)', :class => 'btn btn-primary', :onclick => '$("form").submit()' do %>
        <span class="glyphicon glyphicon-floppy-disk"></span>
      <% end %>
    </div>
  </div>
</div>

<%= render 'form', :post => @post %>

app/views/bo/posts/show.html.erb
<% content_for_header I18n.tmodel(Post), tview('post') %>

<div class="row action-buttons">
  <div class="col-md-7">
    <%= link_to I18n.tbtn('list_of_posts'), bo_posts_path, :class => 'btn btn-default' %>
  </div>
  <div class="col-md-5 align-right">
    <div class="btn-group">
      <%= link_to edit_bo_post_path(@post), :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
      <%= link_to bo_post_path(@post), :class => 'btn btn-danger', :confirm => I18n.tmsg('are_you_sure'), :method => :delete do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </div>
  </div>
</div>

<% unless @post.featured_image.blank? %>
  <div class="row">
    <div class="col-md-12 text-middle">
      <div>
        <%= image_tag @post.featured_image(:large), :class => 'img-rounded img-responsive inline-block'%>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal">
      <dt><%= I18n.tattr(Post, :status) %></dt>
      <dd><%= label_by_post_status @post.status %></dd>
      <dt><%= I18n.tattr(Post, :published_at) %></dt>
      <dd><%= @post.published_at %></dd>
      <dt><%= I18n.tattr(Post, :category) %></dt>
      <dd><%= @post.category.name unless @post.category.blank? %></dd>
      <dt><%= I18n.tattr(Post, :tags) %></dt>
      <dd><%= tag_list @post.tags %></dd>
      <dt><%= I18n.tattr(Post, :title) %></dt>
      <dd><%= @post.title %></dd>
      <dt><%= I18n.tattr(Post, :intro_text) %></dt>
      <dd><%= @post.intro_text %></dd>
      <dt><%= I18n.tattr(Post, :gallery) %></dt>
      <dd><%= link_to @post.gallery.name, bo_gallery_path(@post.gallery) unless @post.gallery.blank? %></dd>
      <dt><%= I18n.tattr(Post, :body_html) %></dt>
      <dd><%= @post.body_html.html_safe %></dd>
    </dl>
  </div>
</div>