config/routes.rb
Site::Application.routes.draw do
  
  root :to => "posts#index"
  
  match 'blog'      => "posts#index", :as => :blog
  match "/blog/:id" => "posts#show",  :as => :post
  
  match 'search'  => "static#search", :as => :search
  
  resources :user_sessions
  match 'login'   => "user_sessions#new",     :as => :login
  match 'logout'  => "user_sessions#destroy", :as => :logout
  
  namespace :bo do
    match 'dashboard' => "dashboard#index"
    resources :users
    resources :tags
    resources :categories
    resources :posts
    resources :images
    resources :galleries do 
      match "/add_image/:id"    => "galleries#add_image",     :via => :post,    :as => :add_image
      match "/delete_image/:id" => "galleries#delete_image",  :via => :delete,  :as => :delete_image
    end
    namespace :ajax do
      post 'kramdown_to_html' => 'base#kramdown_to_html'
      resources :galleries, :only => [] do 
        match "/image_pos/:id"    => "galleries#image_pos", :via => :post, :as => :image_pos
      end
    end
  end
  
  mathjax 'mathjax'

  

end

app/models/image.rb
class Image < ActiveRecord::Base
  STYLES = {:medium => '500x350#', :thumb => "100x100#"}
  
  attr_accessible   :image, :name, :alt
  has_attached_file :image, :styles => STYLES
  
#  has_and_belongs_to_many :galleries, :uniq => true
  has_many :gallery_images, :dependent => :destroy
  has_many :galleries, :through => :gallery_images, :uniq => true
  
  validates_attachment :image, :presence => true,
  :content_type => { :content_type => %w"image/jpg image/jpeg image/pjpeg image/gif image/png image/svg+xml image/tiff" },
  :size => { :in => 0..4.megabytes }
end

app/controllers/bo/ajax/base_controller.rb
class Bo::Ajax::BaseController < Bo::BaseController
  layout false
  
  def kramdown_to_html
    str = params[:str]
    html = Kramdown::Document.new(str, :input => 'kramdown').to_html
    render :text => html
  end
end

app/controllers/bo/ajax/galleries_controller.rb
class Bo::Ajax::GalleriesController < Bo::Ajax::BaseController
  
  def image_pos
    gallery = Gallery.find(params[:gallery_id])
    image = Image.find(params[:id])
    
    gallery_image = gallery.gallery_images.where(:image_id => image.id).first
    pos = params[:pos].to_i
    
    if gallery_image.blank? || pos.blank?
      text = ""
      text += "gallery_image is blank" if gallery_image.blank?
      text += ", pos is blank" if pos.blank?
      text += ", gallery is #{gallery.id}"
      text += ", image is #{image.id}"
      
      render :json => { :status => false, :error => text}
    else
      gallery_image.insert_at(pos)
      render :json => { :status => true}
    end
  end
  
end

app/controllers/bo/ajax_controller.rb
class Bo::AjaxController < Bo::BaseController
  layout :false
  
  def kramdown_to_html
    str = params[:str]
    html = Kramdown::Document.new(str, :input => 'kramdown').to_html
    render :text => html
  end
end

app/controllers/bo/base_controller.rb
class Bo::BaseController < ApplicationController
  layout 'application_bo'
  before_filter :require_user
end

app/controllers/bo/categories_controller.rb
class Bo::CategoriesController < Bo::BaseController
  def index
    @categories = Category.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
   
    if @category.save
      redirect_to [:bo, @category], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Category))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
   
    if @category.update_attributes(params[:category])
      redirect_to [:bo, @category], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Category))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
   
    redirect_to bo_categories_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Category))
  end
end

app/controllers/bo/dashboard_controller.rb
class Bo::DashboardController < Bo::BaseController
  def index
  end
end

app/controllers/bo/galleries_controller.rb
class Bo::GalleriesController < Bo::BaseController
  def index
    @galleries = Gallery.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @gallery = Gallery.find(params[:id])
    @images = Image.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def new
    @gallery = Gallery.new
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end
  
  def create
    @gallery = Gallery.new(params[:gallery])
   
    if @gallery.save
      redirect_to [:bo, @gallery], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Gallery))
    else
      render :action => "new" 
    end
  end
  
  def update
    @gallery = Gallery.find(params[:id])
   
    if @gallery.update_attributes(params[:gallery])
      redirect_to [:bo, @gallery], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Gallery))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
   
    redirect_to bo_galleries_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Gallery))
  end
  
  def add_image
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.find(params[:id])
    
    @gallery.images << @image
    redirect_to bo_gallery_url(@gallery, :page => params[:page])
  end
  
  def delete_image
    @gallery = params[:gallery_id] ? Gallery.find(params[:gallery_id]) : nil
    @image = Image.find(params[:id])
    
    @gallery.images.delete(@image)
    redirect_to bo_gallery_url(@gallery, :page => params[:page])
  end
  
end

app/controllers/bo/images_controller.rb
class Bo::ImagesController < Bo::BaseController
  def index
    @images = Image.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @image = Image.find(params[:id])
  end
  
  def new
    @image = Image.new
  end
  
  def create
    @image = Image.new(params[:image])
    
    if @image.save
      redirect_to [:bo, @image], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Image))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @image = Image.find(params[:id])
  end
  
  def update
    @image = Image.find(params[:id])
   
    if @image.update_attributes(params[:image])
      redirect_to [:bo, @image], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Image))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @image = Image.find(params[:id])

    @image.destroy
    redirect_to bo_images_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Image))
  end
end

app/controllers/bo/posts_controller.rb
class Bo::PostsController < Bo::BaseController
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE).order('published_at DESC')
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
    @post.tag_names = @post.tag_selectize_values
  end
  
  def create
    @post = Post.new(params[:post])
   
    if @post.save
      redirect_to [:bo, @post], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Post))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    @post.tag_names = @post.tag_selectize_values
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update_attributes(params[:post])
      redirect_to [:bo, @post], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Post))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
   
    redirect_to bo_posts_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Post))
  end
end

app/controllers/bo/tags_controller.rb
class Bo::TagsController < Bo::BaseController
  def index
    @tags = Tag.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @tag = Tag.find(params[:id])
  end
  
  def new
    @tag = Tag.new
  end
  
  def create
    @tag = Tag.new(params[:tag])
   
    if @tag.save
      redirect_to [:bo, @tag], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(Tag))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @tag = Tag.find(params[:id])
  end
  
  def update
    @tag = Tag.find(params[:id])
   
    if @tag.update_attributes(params[:tag])
      redirect_to [:bo, @tag], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(Tag))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
   
    redirect_to bo_tags_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(Tag))
  end
end

app/controllers/bo/users_controller.rb
class Bo::UsersController < Bo::BaseController
  def index
    @users = User.paginate(:page => params[:page], :per_page => ELEMS_PER_PAGE)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
   
    if @user.save
      redirect_to [:bo, @user], :notice => I18n.tmsg('successfully_created', :model => I18n.tmodel(User))
    else
      render :action => "new" 
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
   
    if @user.update_attributes(params[:user])
      redirect_to [:bo, @user], :notice => I18n.tmsg('successfully_updated', :model => I18n.tmodel(User))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
   
    redirect_to bo_users_url, :notice => I18n.tmsg('successfully_destroyed', :model => I18n.tmodel(User))
  end
end

app/helpers/bo/categories_helper.rb
module Bo::CategoriesHelper
end

app/helpers/bo/images_helper.rb
module Bo::ImagesHelper
  def image_dropdown_styles_button image
    btn = button_tag :class => 'btn btn-default dropdown-toggle', 'data-toggle' => "dropdown" do
      content_tag(:span, nil, :class => "glyphicon glyphicon-paperclip") +
      " " +
      content_tag(:span, nil, :class => 'caret')
    end
    
    links = content_tag :ul, :class => 'dropdown-menu align-left', :role => 'menu' do
      Image::STYLES.each do |key, value|
        concat content_tag(:li, (link_to key, 'javascript:void(0)', :onclick => "window.prompt ('#{tview('copy_to_clipboard')}', '#{path_to_image image.image.url(key)}');"))
      end
      concat content_tag(:li, (link_to 'original', 'javascript:void(0)', :onclick => "window.prompt ('#{tview('copy_to_clipboard')}', '#{path_to_image image.image.url}');"))
    end
    
    content_tag(:div, btn+links, :class => 'btn-group')
  end
end

app/helpers/bo/posts_helper.rb
module Bo::PostsHelper
  
  #
  #
  #
  def label_by_post_status status
    label_type = case status
      when :published then 'label-success'
      when :pending_review then 'label-warning'
      when :draft then 'label-default'
      else '' end
    
    "<span class='label #{label_type}'>#{Post.human_enum_name :statuses, status}</span>".html_safe
  end
  
  #
  #
  #
  def tag_list tags
    html = '<div class="tag-list">'
    html += tags.map.each{|tag| "<span class='tag'>#{tag.name}</span>"}.join(' ')
    html += '</div>'
    html.html_safe
  end
  
end

app/helpers/bo/tags_helper.rb
module Bo::TagsHelper
end

app/helpers/bo/users_helper.rb
module Bo::UsersHelper
end

app/views/bo/images/_form.html.erb
<%# PARAMS: image
%>


<%= render 'bo/shared/errors', :target => image %>

<div class="row">
  <div class="col-md-8">
    <%= form_for [:bo, image], :html => {:class => 'form-horizontal'} do |f| %>
    <form class="form-horizontal" role="form">
      <div class="form-group">
        <%= f.label :image, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :image, :class => '' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :name, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :name, :class => 'form-control', :autofocus => true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :alt, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :alt, :class => 'form-control' %>
        </div>
      </div>
    </form>
    <% end %>
  </div>
</div>

app/views/bo/images/edit.html.erb
<% content_for_header I18n.tmodel(Image), tview('edit_image') %>

<div class="row action-buttons">
  <div class="col-md-7">
    <%= link_to I18n.tbtn('cancel'), bo_image_path(@image), :class => 'btn btn-default' %>
  </div>
  <div class="col-md-5 align-right">
    <div class="btn-group">
      <%= link_to 'javascript:void(0)', :class => 'btn btn-primary', :onclick => '$("form").submit()' do %>
        <span class="glyphicon glyphicon-floppy-disk"></span>
      <% end %>
    </div>
  </div>
</div>

<%= render 'form', :image => @image %><br />

app/views/bo/images/index.html.erb
<% content_for_header I18n.tmodel(Image), tview('list_of_images') %>

<div class="row">
  <div class="col-md-12">
    <%= link_to I18n.tbtn('add_new'), new_bo_image_path, :class => 'btn btn-default' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-condensed table-striped">
      <thead>
        <tr>
          <th><%= I18n.tattr(Image, :image) %></th>
          <th><%= I18n.tattr(Image, :name) %></th>
          <th><%= I18n.tattr(Image, :alt) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% for image in @images %>
          <tr>
            <td>
              <%= link_to image.image.url, :class => 'magnific-popup-zoom', :title => image.name do %>
                <%= image_tag image.image.url(:thumb), :class => 'img-rounded image-list-thumb' %>
              <% end %>
            </td>
            <td><%= image.name %></td>
            <td><%= image.alt %></td>
            <td class="align-right btn-group-for-4-btns">
              <div class="btn-group">
                <%= image_dropdown_styles_button image  %>
                <%= link_to bo_image_path(image), :class => 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-eye-open"></span>
                <% end %>
                <%= link_to edit_bo_image_path(image), :class => 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                <% end %>
                <%= link_to bo_image_path(image), :class => 'btn btn-danger', :confirm => I18n.tmsg('are_you_sure'), :method => :delete do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/bo/images/new.html.erb
<% content_for_header I18n.tmodel(Image), tview('new_image') %>

<div class="row action-buttons">
  <div class="col-md-7">
    <%= link_to I18n.tbtn('cancel'), bo_images_path, :class => 'btn btn-default' %>
  </div>
  <div class="col-md-5 align-right">
    <div class="btn-group">
      <%= link_to 'javascript:void(0)', :class => 'btn btn-primary', :onclick => '$("form").submit()' do %>
        <span class="glyphicon glyphicon-floppy-disk"></span>
      <% end %>
    </div>
  </div>
</div>

<%= render 'form', :image => @image %>

app/views/bo/images/show.html.erb
<% content_for_header I18n.tmodel(Image), tview('image') %>

<div class="row action-buttons">
  <div class="col-md-7">
    <%= link_to I18n.tbtn('list_of_images'), bo_images_path, :class => 'btn btn-default' %>
  </div>
  <div class="col-md-5 align-right">
    <div class="btn-group">
      <%= image_dropdown_styles_button @image  %>
      <%= link_to edit_bo_image_path(@image), :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
      <%= link_to bo_image_path(@image), :class => 'btn btn-danger', :confirm => I18n.tmsg('are_you_sure'), :method => :delete do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal">
      <dt><%= I18n.tattr(Image, :name) %></dt>
      <dd><%= @image.name %></dd>
      <dt><%= I18n.tattr(Image, :alt) %></dt>
      <dd><%= @image.alt %></dd>
      <dt><%= I18n.tattr(Image, :image) %></dt>
      <dd>
        <%= link_to @image.image.url, :class => 'magnific-popup-zoom', :title => @image.name do %>
          <%= image_tag @image.image.url(:thumb) %>
        <% end %>
      </dd>
    </dl>
  </div>
</div>